filesets:
    includes:
        - templates
        - public
        - conf
        - LICENSE
        - README.md
        - README_ZH.md
        - start.bat
        - start.sh
    excludes:
        - \.git
